version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      compatible-patches:
        update-types:
          - patch
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: deps
    labels:
      - dependencies
