sonar.projectKey=aguther_rundflug-leitstand
sonar.organization=aguther
sonar.projectName=rundflug-leitstand
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=apps,packages,scripts
sonar.tests=apps,packages,scripts
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.worker-spec.ts
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/*.worker-spec.ts,**/dist/**,**/.wrangler/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
