import { z } from "zod";

import { eventSnapshotSchema } from "./event-auth";
import {
  operationalPlanEffectModeSchema,
  operationalPlanKindSchema,
  operationalPlanScopeSchema,
  operationalPlanStartModeSchema,
  operationalPlanStatusSchema,
  recurringOperationalRuleKindSchema,
  recurringOperationalRuleScopeSchema,
  recurringOperationalRuleStatusSchema,
  recurringOperationalRuleTriggerSchema,
} from "./operation-command-planning";
import { turnaroundPhaseOverrideValueSchema } from "./schema-helpers";
import { gateDisplayFilterSchema } from "./shared";
import { ticketGroupRecallProjectionSchema } from "./tickets-public-status";

export const productOperationalSummarySchema = z.object({
  id: z.string(),
  code: z.string(),
  name: z.string(),
  publicDescription: z.string(),
  resourceGroupId: z.string(),
  resourceGroupName: z.string(),
  resourceGroupStatus: z.enum(["ACTIVE", "PAUSED", "INTERRUPTED", "ENDED"]),
  resourceGroupOperationalNote: z.string(),
  priceCents: z.number().int().nonnegative(),
  gateId: z.string().min(1),
  gateLabel: z.string().min(1),
  childCompanionRequired: z.boolean(),
  weightClasses: z.array(z.enum(["NOT_CAPTURED", "CHILD", "NORMAL", "HEAVY", "INDIVIDUAL"])),
  sortOrder: z.number().int().nonnegative(),
  saleEnabled: z.boolean(),
  referenceCapacity: z.number().int().positive(),
  // Operative Produkt-Planzeit vom bestätigten Offblock bis zum bestätigten Onblock.
  referenceDurationMinutes: z.number().int().positive(),
  // Gegenüber Gästen kommunizierte Produktzeit ohne Wirkung auf die operative Prognose.
  promisedFlightMinutes: z.number().int().positive(),
  plannedBoardingMinutesOverride: turnaroundPhaseOverrideValueSchema,
  plannedDeboardingMinutesOverride: turnaroundPhaseOverrideValueSchema,
  plannedBufferMinutesOverride: turnaroundPhaseOverrideValueSchema,
  effectiveTurnaroundProfile: z.object({
    boarding: z.object({
      valueMinutes: z.number().int().nonnegative(),
      sourceLevel: z.enum(["AIRCRAFT_PRODUCT", "PRODUCT", "EVENT"]),
      sourceId: z.string(),
    }),
    deboarding: z.object({
      valueMinutes: z.number().int().nonnegative(),
      sourceLevel: z.enum(["AIRCRAFT_PRODUCT", "PRODUCT", "EVENT"]),
      sourceId: z.string(),
    }),
    buffer: z.object({
      valueMinutes: z.number().int().nonnegative(),
      sourceLevel: z.enum(["AIRCRAFT_PRODUCT", "PRODUCT", "EVENT"]),
      sourceId: z.string(),
    }),
    totalGroundMinutes: z.number().int().nonnegative(),
  }),
  queuedTickets: z.number().int().nonnegative(),
  resourceGroupOpenTickets: z.number().int().nonnegative(),
  estimatedWaitLowerMinutes: z.number().int().nonnegative(),
  estimatedWaitUpperMinutes: z.number().int().nonnegative(),
  nextBoardingWindowLowerAt: z.iso.datetime().nullable(),
  nextBoardingWindowUpperAt: z.iso.datetime().nullable(),
  remainingSellableSeats: z.number().int().nonnegative(),
  projectedSeats: z.number().int().nonnegative(),
  capacityStatus: z.enum(["AVAILABLE", "LIMITED", "MANUAL_REVIEW", "SOLD_OUT"]),
  saleRecommended: z.boolean(),
  saleClosesAt: z.string().nullable(),
  capacityWarningThreshold: z.number().int().nonnegative(),
  capacityCriticalThreshold: z.number().int().nonnegative(),
  predictionQuality: z.enum(["STABLE", "CHANGING", "UNCERTAIN"]),
});

const rotationBookingGroupSchema = z
  .object({
    id: z.string(),
    communicationNumber: z.number().int().positive(),
    soldAt: z.string(),
    ticketCount: z.number().int().positive(),
    presentCount: z.number().int().nonnegative(),
    partNumber: z.number().int().positive().default(1),
    partCount: z.number().int().positive().default(1),
  })
  .refine((group) => group.partNumber <= group.partCount, {
    message: "Booking group part number must not exceed its part count",
    path: ["partNumber"],
  });

export const rotationOperationalSummarySchema = z.object({
  id: z.string(),
  version: z.number().int().nonnegative(),
  flightGroupId: z.string(),
  communicationNumber: z.number().int().positive(),
  communicationLabel: z.string().regex(/^[A-Z0-9-]+-\d{3,}$/),
  queuePosition: z.number().int().positive(),
  productCode: z.string(),
  productName: z.string(),
  status: z.enum(["DRAFT", "CALLED", "IN_FLIGHT", "LANDED", "COMPLETED"]),
  bookingGroups: z.array(rotationBookingGroupSchema).default([]),
  ticketGroupId: z.string(),
  gateId: z.string().min(1),
  gateLabel: z.string().min(1),
  aircraftId: z.string().nullable(),
  aircraftRegistration: z.string().nullable(),
  pilotId: z.string().nullable(),
  pilotOperationalCode: z.string().nullable(),
  suggestedPilotId: z.string().nullable(),
  suggestedPilotOperationalCode: z.string().nullable(),
  suggestedAircraftId: z.string().nullable(),
  suggestedAircraftRegistration: z.string().nullable(),
  ticketCount: z.number().int().nonnegative(),
  baselineCapacity: z.number().int().positive(),
  usableCapacity: z.number().int().positive(),
  capacityReduced: z.boolean(),
  estimatedPassengerPayloadKg: z.number().positive().nullable(),
  predictedLowerMinutes: z.number().int().nonnegative().nullable(),
  predictedUpperMinutes: z.number().int().nonnegative().nullable(),
  boardingWindowLowerAt: z.iso.datetime().nullable(),
  boardingWindowUpperAt: z.iso.datetime().nullable(),
  precalledAt: z.string().nullable().optional(),
  precallDecision: z
    .object({
      status: z.enum(["WAITING", "PREPARE", "GO_TO_GATE"]),
      reason: z.enum([
        "ELIGIBLE",
        "DISABLED",
        "OPERATIONS_BLOCKED",
        "NOT_QUEUE_FRONT",
        "ALREADY_PRECALLED",
        "NO_FORECAST_CAPACITY",
        "NO_FITTING_AIRCRAFT",
        "NOT_IN_NEAR_DISPATCH_BATCH",
        "GATE_CAPACITY_COVERED",
        "WAITING_FOR_PRODUCT_FAIRNESS",
        "WAITING_FOR_FITTING_LANE",
        "COMMITMENT_LOCKED",
        "DISPATCH_PLAN_STALE",
        "TOO_EARLY",
      ]),
      decidedAt: z.string(),
      predictedBoardingAt: z.string().nullable(),
      adaptiveLeadMinutes: z.number().int().nonnegative().nullable(),
      gateId: z.string().nullable().default(null),
      adaptiveBaseLeadMinutes: z.number().int().nonnegative().nullable().default(null),
      gateTravelLeadMinutes: z.number().int().min(0).max(30).nullable().default(null),
      effectiveLeadMinutes: z.number().int().nonnegative().nullable().default(null),
      boardingWindowLowerAt: z.string().nullable().default(null),
      boardingWindowUpperAt: z.string().nullable().default(null),
    })
    .nullable()
    .optional(),
  calledAt: z.string().nullable(),
  dispatchPlan: z
    .object({
      planId: z.string(),
      revision: z.string(),
      batchId: z.string().nullable(),
      dispatchOrder: z.number().int().positive().nullable(),
      wave: z.number().int().positive().nullable(),
      laneId: z.string().nullable(),
      groupIds: z.array(z.string()),
      occupiedSeats: z.number().int().positive().nullable(),
      availableSeats: z.number().int().nonnegative().nullable(),
      commitmentLevel: z.enum(["WAITING", "PREPARE", "COME_TO_FLIGHT_LINE"]).nullable(),
      decisionReasons: z.array(
        z.enum([
          "HARD_COMMITMENT",
          "MUST_SERVE_MAX_WAIT",
          "MUST_SERVE_MAX_OVERTAKES",
          "PRODUCT_FAIRNESS",
          "CAPACITY_OPTIMIZED",
          "QUEUE_ORDER",
          "PLAN_STABILITY",
          "STANDBY_PRIORITY",
        ]),
      ),
      confirmedOvertakeCount: z.number().int().nonnegative().default(0),
      projectedOvertakeCount: z.number().int().nonnegative(),
      unplannedReason: z
        .enum([
          "NO_FORECAST_CAPACITY",
          "WAITING_FOR_FITTING_LANE",
          "WAITING_FOR_PRODUCT_FAIRNESS",
          "NOT_IN_NEAR_DISPATCH_BATCH",
          "COMMITMENT_LOCKED",
          "ATTENDANCE_MISSING",
          "ATTENDANCE_CLARIFICATION",
          "UNKNOWN_RESOURCE_RETURN",
        ])
        .nullable(),
    })
    .nullable()
    .optional(),
  deferralCount: z.number().int().nonnegative(),
  operationalNote: z.string(),
  timeline: z.object({
    planned: z.object({
      boardingAt: z.string().nullable(),
      departureAt: z.string().nullable(),
      landingAt: z.string().nullable(),
      completionAt: z.string().nullable(),
    }),
    predicted: z.object({
      boardingAt: z.string().nullable(),
      departureAt: z.string().nullable(),
      landingAt: z.string().nullable(),
      completionAt: z.string().nullable(),
    }),
    actual: z.object({
      boardingAt: z.string().nullable(),
      departureAt: z.string().nullable(),
      landingAt: z.string().nullable(),
      completionAt: z.string().nullable(),
    }),
    predictionQuality: z.enum(["STABLE", "CHANGING", "UNCERTAIN"]).nullable(),
    predictionUpdatedAt: z.string().nullable(),
    forecastAssumedAircraftId: z.string().nullable().optional(),
    extendsBeyondOperationsEnd: z.boolean(),
    overtimeMinutes: z.number().int().nonnegative(),
    effectiveTurnaroundProfile: productOperationalSummarySchema.shape.effectiveTurnaroundProfile
      .nullable()
      .optional(),
  }),
  tickets: z.array(
    z.object({
      id: z.string(),
      status: z.enum([
        "QUEUED",
        "CHECKED_IN",
        "CALLED",
        "BOARDING",
        "IN_FLIGHT",
        "LANDED",
        "COMPLETED",
        "NO_SHOW",
        "CANCELED",
        "CLARIFICATION",
      ]),
      attendanceStatus: z.enum(["NOT_CHECKED_IN", "CHECKED_IN"]),
    }),
  ),
});

export const aircraftOperationalSummarySchema = z.object({
  id: z.string(),
  version: z.number().int().nonnegative(),
  registration: z.string(),
  aircraftType: z.string(),
  passengerSeats: z.number().int().positive(),
  maximumPassengerPayloadKg: z.number().positive().nullable(),
  operationalState: z.enum([
    "AVAILABLE",
    "BOARDING",
    "IN_FLIGHT",
    "LANDED",
    "TURNAROUND",
    "REFUELING",
    "PAUSED",
    "INTERRUPTED",
    "INACTIVE",
  ]),
  operationalStateChangedAt: z.string(),
  resourceGroupId: z.string(),
  resourceGroupName: z.string(),
  resourceGroupShortCode: z.string(),
  refuelPlanned: z.boolean(),
  rotationsSinceRefuel: z.number().int().nonnegative(),
  refuelReminderThreshold: z.number().int().positive(),
  expectedReviewAt: z.string().nullable(),
  currentPilotId: z.string().nullable(),
  currentPilotOperationalCode: z.string().nullable(),
});

export const pilotOperationalSummarySchema = z.object({
  id: z.string(),
  operationalCode: z.string(),
  operationalNote: z.string(),
  active: z.boolean(),
  paused: z.boolean(),
  pauseExpectedReviewAt: z.string().nullable(),
  currentRotationId: z.string().nullable(),
  currentCommunicationNumber: z.number().int().positive().nullable(),
});

export const plannedOperationalConstraintSchema = z.object({
  id: z.string(),
  version: z.number().int().nonnegative(),
  scopeType: operationalPlanScopeSchema,
  scopeId: z.string(),
  kind: operationalPlanKindSchema,
  effectMode: operationalPlanEffectModeSchema,
  durationMultiplierPercent: z.number().int().min(110).max(300).nullable(),
  startMode: operationalPlanStartModeSchema,
  earliestStartAt: z.string().nullable(),
  latestStartAt: z.string().nullable(),
  afterRotationId: z.string().nullable(),
  minimumDurationMinutes: z.number().int().positive(),
  typicalDurationMinutes: z.number().int().positive(),
  maximumDurationMinutes: z.number().int().positive(),
  status: operationalPlanStatusSchema,
  publicNote: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
  activatedAt: z.string().nullable(),
  clearedAt: z.string().nullable(),
  canceledAt: z.string().nullable(),
  recurringRuleId: z.string().nullable().default(null),
  recurrenceSequence: z.number().int().positive().nullable().default(null),
});
export type PlannedOperationalConstraint = z.infer<typeof plannedOperationalConstraintSchema>;

export const recurringOperationalRuleSchema = z.object({
  id: z.string(),
  operationDayId: z.string(),
  version: z.number().int().nonnegative(),
  scopeType: recurringOperationalRuleScopeSchema,
  scopeId: z.string(),
  kind: recurringOperationalRuleKindSchema,
  triggerMetric: recurringOperationalRuleTriggerSchema,
  intervalValue: z.number().int().positive(),
  progressValue: z.number().int().nonnegative(),
  minimumDurationMinutes: z.number().int().positive(),
  typicalDurationMinutes: z.number().int().positive(),
  maximumDurationMinutes: z.number().int().positive(),
  status: recurringOperationalRuleStatusSchema,
  sequenceNumber: z.number().int().nonnegative(),
  openPlannedOperationId: z.string().nullable(),
  reason: z.string().nullable(),
  lastResetAt: z.string(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type RecurringOperationalRule = z.infer<typeof recurringOperationalRuleSchema>;

export const operationBoardSchema = z.object({
  currentDeviceRole: z.enum(["CASHIER", "FLIGHT_LINE", "FLIGHT_DIRECTOR", "ADMIN"]),
  event: eventSnapshotSchema,
  products: z.array(productOperationalSummarySchema),
  aircraftProductTurnaroundOverrides: z
    .array(
      z.object({
        aircraftId: z.string(),
        productId: z.string(),
        version: z.number().int().nonnegative(),
        plannedBoardingMinutesOverride: turnaroundPhaseOverrideValueSchema,
        plannedDeboardingMinutesOverride: turnaroundPhaseOverrideValueSchema,
        plannedBufferMinutesOverride: turnaroundPhaseOverrideValueSchema,
        effectiveTurnaroundProfile:
          productOperationalSummarySchema.shape.effectiveTurnaroundProfile,
      }),
    )
    .default([]),
  rotations: z.array(rotationOperationalSummarySchema),
  queueGroups: z
    .array(
      z.object({
        id: z.string(),
        communicationNumber: z.number().int().positive(),
        productId: z.string(),
        productCode: z.string(),
        productName: z.string(),
        resourceGroupId: z.string(),
        gateId: z.string(),
        queueSequence: z.number().int().positive(),
        status: z.string(),
        ticketCount: z.number().int().positive(),
        presentCount: z.number().int().nonnegative(),
        nextSegmentTicketCount: z.number().int().positive().optional(),
        nextSegmentPresentCount: z.number().int().nonnegative().optional(),
        segmentIndex: z.number().int().positive().optional(),
        segmentCount: z.number().int().positive().optional(),
        precalledAt: z.string().nullable().default(null),
        dispatchReservation: z.enum(["OWN", "OTHER"]).nullable().default(null),
        recalledAt: z.string().nullable(),
        recallCount: z.number().int().nonnegative(),
        activeRecall: ticketGroupRecallProjectionSchema.nullable(),
      }),
    )
    .default([]),
  aircraft: z.array(aircraftOperationalSummarySchema),
  assistClaims: z.array(
    z.object({
      aircraftId: z.string(),
      claimedByCurrentOperator: z.boolean(),
      ownerLoginCode: z.string(),
      revision: z.number().int().positive(),
      claimedAt: z.string(),
      expiresAt: z.string(),
    }),
  ),
  pilots: z.array(pilotOperationalSummarySchema),
  plannedOperations: z.array(plannedOperationalConstraintSchema).default([]),
  recurringOperationalRules: z.array(recurringOperationalRuleSchema).default([]),
  gates: z.array(
    z.object({
      id: z.string(),
      label: z.string(),
      gateType: z.enum(["FLIGHT_LINE", "BOARDING", "DISPLAY_ONLY"]),
      active: z.boolean(),
      sortOrder: z.number().int().nonnegative(),
      travelLeadMinutes: z.number().int().min(0).max(30),
      displayFilter: gateDisplayFilterSchema,
      assignedResourceGroupIds: z.array(z.string()),
    }),
  ),
  resourceGroups: z.array(
    z.object({
      id: z.string(),
      version: z.number().int().nonnegative(),
      name: z.string(),
      shortCode: z.string(),
      status: z.enum(["ACTIVE", "PAUSED", "INTERRUPTED", "ENDED"]),
      operationalNote: z.string().trim().max(240),
      gateId: z.string(),
      gateLabel: z.string(),
      referenceCapacity: z.number().int().positive(),
      compatibleAircraftTypes: z.array(z.string()),
      automaticPrecallEnabled: z.boolean(),
      activeAircraftIds: z.array(z.string()),
    }),
  ),
  metrics: z.object({
    openTickets: z.number().int().nonnegative(),
    soldTickets: z.number().int().nonnegative(),
    completedRotations: z.number().int().nonnegative(),
    activeRotations: z.number().int().nonnegative(),
    averageBoardingMinutes: z.number().nonnegative().nullable(),
    averageFlightMinutes: z.number().nonnegative().nullable(),
    averageTurnaroundMinutes: z.number().nonnegative().nullable(),
    averageRotationMinutes: z.number().nonnegative().nullable(),
    averageWaitMinutes: z.number().nonnegative().nullable(),
    informationalRevenueCents: z.number().int().nonnegative(),
    activeDevices: z.number().int().nonnegative(),
    activePushSubscriptions: z.number().int().nonnegative(),
  }),
});
export type OperationBoard = z.infer<typeof operationBoardSchema>;
